[project]
name = "semfile"
version = "0.1.0"
description = "Semantic file search using multimodal embeddings"
readme = "README.md"
authors = [
    { name = "Jibraan Kadri", email = "jibraan.kadri23@gmaill.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-genai",
    "chromadb",
    "click",
    "python-dotenv",
    "pillow",
    "tenacity",
    "fastapi",
    "uvicorn",
]

[project.scripts]
semfile = "semfile.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
